[base]
env_name = common_harvest

[vec]
total_agents = 8176
num_buffers = 8
num_threads = 1

[env]
num_agents = 7
report_interval=1
beam_blocks_movement = True
differentiate_other_agents_in_obs = True
shared_rewards = True
rng = 73

[policy]
hidden_size = 128
num_layers = 4
expansion_factor = 1

[train]
gpus = 1
seed = 42
total_timesteps = 199887008
learning_rate = 0.0028719
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.998449
gae_lambda = 0.9995
replay_ratio = 0.680392
clip_coef = 0.22951
vf_coef = 0.838204
vf_clip_coef = 0.01
max_grad_norm = 0.114736
ent_coef = 1.20085e-05
anneal_ent_coef = 0
min_ent_coef_ratio = 0.1
beta1 = 0.766641
beta2 = 0.999
eps = 3.18567e-06
minibatch_size = 8192
horizon = 128
vtrace_rho_clip = 1
vtrace_c_clip = 1
prio_alpha = 0.181807
prio_beta0 = 0.2
checkpoint_interval = 200


[sweep]
sweep_only = total_timesteps, horizon, learning_rate, ent_coef, gamma, gae_lambda, replay_ratio, clip_coef, vf_clip_coef, vf_coef, max_grad_norm, beta1, eps, prio_alpha
method = Protein 
metric = score
metric_distribution = linear
goal = maximize
max_suggestion_cost = 3600
max_runs = 200
gpus = 0
downsample = 5
use_gpu = True
prune_pareto = True
early_stop_quantile = 0.3

[sweep.train.total_timesteps]
distribution = log_normal
min = 2e8
max = 5e9
scale = time

[sweep.train.horizon]
distribution = uniform_pow2
min = 8
max = 128
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
max = 0.1
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
max = 0.2
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.5
max = 0.9995
scale = auto

[sweep.train.replay_ratio]
distribution = uniform
min = 0.25
max = 4.0
scale = auto

[sweep.train.clip_coef]
distribution = uniform
# Lower clip is sometimes better but less stable
min = 0.01
max = 1.0
scale = auto

# Optimal vf clip can be lower than 0.1,
# but this results in jank unstable runs
[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.01
max = 5.0
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.beta1]
distribution = logit_normal
min = 0.5
max = 0.999
scale = auto

[sweep.train.eps]
distribution = log_normal
min = 1e-14
max = 1e-4
scale = auto

[sweep.train.prio_alpha]
distribution = uniform 
min = 0.0
max = 1.0
scale = auto


